[package]
name = "octopus-gui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "octopus_gui"
path = "src/main.rs"

[dependencies]
octopus-engine = { path = "../engine" }
eframe = "0.29"
ctrlc = "3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "processenv", "winbase"] }
