[package]
name = "cli_ui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cli_ui"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.24"
serde_json = "1"
futures-util = "0.3"

[profile.release]
opt-level = 2
strip = true
lto = true
codegen-units = 1
